### ISSUE TITLE
config.example.json doesn't cover everything

### ISSUE THREAD

**Issue by ImagineGamingPlay** [ImagineGamingPlay/Cheeku-Development#28]
config.example.json doesn't have all the placeholders this project requires to run freely without editing the files not in git.ignore. I can't understand how this went unnoticed. please fix

**Comment by ImagineGamingPlay** [comment]
Example, modmail.js
https://github.com/ImagineGamingPlay/Cheeku-Development/blob/main/src/functions/modmail.js

**Comment by NightSling** [comment]
@GoodBoyNeon can you please fill in the details of modmail as I have no clue on what we did there

**Comment by GoodBoyNeon** [comment]
Will do

**Comment by GoodBoyNeon** [comment]
I don't have the source code of cheeku. Need some help @TECHNOPAWS

**Comment by GoodBoyNeon** [comment]
nvm I have backups on my disk

**Comment by GoodBoyNeon** [comment]
I do not see any placeholders missing, probably because my config.json is really old. Can anyone send me the updated one?

**Comment by ImagineGamingPlay** [comment]
@GoodBoyNeon refer to config.example.example

**Comment by ImagineGamingPlay** [comment]
[909d8ba](https://github.com/ImagineGamingPlay/Cheeku-Development/commit/909d8bac49191cef588f3a5149077cd4fd61f9ef) I fixed it myself
