### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by TECHNOPAWS** [ImagineGamingPlay/Cheeku-Development#8]
You guys leaked the url of the webhook for delete logs

**Comment by TECHNOPAWS** [comment]
U guys leaked the webhook url of the delete log ;-;

**Comment by NightSling** [comment]
Thanks man will get sorted asap!

**Comment by GoodBoyNeon** [comment]
Yoo never thought of that! Good thing to mention about, thanks!

**Comment by TECHNOPAWS** [comment]
lol np
